
variable "proxmox_api_password" {
  type      = string
  sensitive = true
}

variable "proxmox_api_user" {
  type = string
}

variable "proxmox_host" {
  type = string
}

variable "proxmox_node" {
  type = string
}
# The "legacy_isotime" function has been provided for backwards compatability, but we recommend switching to the timestamp and formatdate functions.

source "proxmox-iso" "autogenerated_1" {
  boot_command            = ["<esc><wait>auto url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<enter>"]
  boot_wait               = "10s"
  cloud_init              = true
  cloud_init_storage_pool = "local"
  cores                   = "2"
  cpu_type                = "EPYC"
  disks {
    disk_size         = "10G"
    format            = "raw"
    storage_pool      = "local-lvm"
    storage_pool_type = "lvm-thin"
    type              = "scsi"
  }
  http_directory           = "./"
  insecure_skip_tls_verify = true
  iso_file                 = "local:iso/debian-10.4.0-amd64-netinst.iso"
  memory                   = "2048"
  network_adapters {
    bridge   = "vmbr0"
    firewall = true
    model    = "virtio"
  }
  node                 = "${var.proxmox_node}"
  os                   = "l26"
  password             = "${var.proxmox_api_password}"
  proxmox_url          = "https://${var.proxmox_host}/api2/json"
  scsi_controller      = "virtio-scsi-single"
  sockets              = "1"
  ssh_password         = "packer"
  ssh_username         = "root"
  template_description = "Debian 10 cloud-init template. Built on ${legacy_isotime("2006-01-02T15:04:05Z")}"
  unmount_iso          = true
  username             = "${var.proxmox_api_user}"
  vm_name              = "debian-10.4.0-amd64"
}

build {
  sources = ["source.proxmox-iso.autogenerated_1"]

  provisioner "file" {
    destination = "/etc/cloud/cloud.cfg"
    source      = "cloud.cfg"
  }

}
