---
- name: "Manage proxmox node(s)"
  hosts: "proxmox"
  gather_facts: false
  roles:
    - ../roles/020_proxmox_node_users
  vars:
    roles:
      - proxmox_role_name: Automation
        privs: VM.Allocate VM.Clone VM.Config.CDROM VM.Config.CPU VM.Config.Cloudinit VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Console VM.Monitor VM.Audit VM.PowerMgmt Datastore.AllocateSpace Datastore.Audit Sys.Modify
    users:
      - proxmox_user_name: automation@pve
        proxmox_role_name: Automation
      - proxmox_user_name: notroot@pve
        proxmox_role_name: Administrator

    # packages_to_install:
    #   - "jq"
