---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
- name: "Install apt packages"
  apt:
    name: "{{ packages_to_install }}"
