#cloud-config
hostname: u2004-server-ansible
manage_etc_hosts: true
fqdn: ubuntu-server-2004.local.lab
timezone: America/Chicago

#####
# Add groups to the system
# The following example adds the ubuntu group with members 'root' and 'sys'
# and the empty group notroot.
groups:
  - notroot
  # - ubuntu: [root, sys]
  # - notroot: [notroot]
#####

#####
# https://github.com/canonical/cloud-init/blob/main/doc/examples/cloud-config-user-groups.txt
#####
# Add users to the system. Users are added after groups are added.
# Note: Most of these configuration options will not be honored if the user
#       already exists. Following options are the exceptions and they are
#       applicable on already-existing users:
#       - 'plain_text_passwd', 'hashed_passwd', 'lock_passwd', 'sudo',
#         'ssh_authorized_keys', 'ssh_redirect_user'.
# Default user creation:
#
# Unless you define users, you will get a 'ubuntu' user on ubuntu systems with the
# legacy permission (no password sudo, locked user, etc). If however, you want
# to have the 'ubuntu' user in addition to other users, you need to instruct
# cloud-init that you also want the default user. To do this use the following
# syntax:
#   users:
#     - default
#     - bob
#     - ....
#  foobar: ...
#
# users[0] (the first user in users) overrides the user directive.
#
# The 'default' user above references the distro's config:
# system_info:
#   default_user:
#     name: Ubuntu
#     plain_text_passwd: 'ubuntu'
#     home: /home/ubuntu
#     shell: /bin/bash
#     lock_passwd: True
#     gecos: Ubuntu
#     groups: [adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev]
#####

# user: notroot
# # generate with mkpasswd -m sha-512 --rounds=4096 $(pass Homelab/proxmox/users/automation@pve)
# # password: obQ2uKo7pGgRHE15shmXNsJzk
# password: "$6$rounds=4096$FBDc7Tr2pawaO$CvC8LS3ItljMWGUtZHc0XXxs3x16lFeoeYrHQcyUqF6dc8HDacJ39APzCwrTDVaenjD1SZgINTg9noLoGHx2V1"

users:
  - default
  - name: notroot
    gecos: NotRoot
    # passwd: notroot
    # passwd: obQ2uKo7pGgRHE15shmXNsJzk
    passwd: $6$rounds=4096$FBDc7Tr2pawaO$CvC8LS3ItljMWGUtZHc0XXxs3x16lFeoeYrHQcyUqF6dc8HDacJ39APzCwrTDVaenjD1SZgINTg9noLoGHx2V1
    lock_passwd: false
    primary-group: notroot
    groups: notroot,adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev,lxd
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    # ssh_import_id: "gh:proxmox"
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHNqLSuUBuN23f+/h+hVEA+0r7+mdX5+3D99g9tJoE38 proxmox
#####

#####
#https://github.com/canonical/cloud-init/blob/main/doc/examples/cloud-config-ssh-keys.txt
#####
# By default, the fingerprints of the authorized keys for the users
# cloud-init adds are printed to the console. Setting
# no_ssh_fingerprints to true suppresses this output.
no_ssh_fingerprints: true

# By default, (most) ssh host keys are printed to the console. Setting
# emit_keys_to_console to false suppresses this output.
ssh:
  # emit_keys_to_console: false
  # For now we install openssh-server during package installs
  install-server: true
  allow-pw: true

ssh_pwauth: yes

# # add each entry to ~/.ssh/authorized_keys for the configured user or the
# # first user defined in the user definition directive.
# ssh_authorized_keys:
#   - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHNqLSuUBuN23f+/h+hVEA+0r7+mdX5+3D99g9tJoE38 proxmox

chpasswd:
  expire: False
# # list: |
# #   ubuntu:$6$JRWPNckuCpg$kb3/eoXAgiYOiBEFejpB.kItBpnRrEqrxYtuQQZoDrlmqF4.mrhUKFbnLqAZrSSUsay5eDjUM8.b6/5eUr.Ca0
# #   notroot:$6$iLOJTxmjd$dm36v8Z8vxwZQe7gCy.XSoex.g2ZNnwdi7KzYjOdJiZbrYRC7BEA2YSBHN4r.nqjuX07EUdvCjYPq72jWSfnB/
# #   root:$6$fn/XMZ7Dtm.$GUy5gcVK0zaNPv8yFzNWN6uufRKgoMSJJSXE3wYJTfWuVpzYkbxNWYrhL0hG2wILWOQXsRtzXNxtt3vQRYQOA/

package_update: true
package_upgrade: true
packages:
  - curl
  - wget
  - lsb-release
  - openssh-server
  - ca-certificates # https://askubuntu.com/questions/857476/what-is-the-use-purpose-of-the-ca-certificates-package
  - ntp # network time protocol
  - vim
  - jq
  - zip
  - unzip
  - gnupg2
  - software-properties-common # https://askubuntu.com/questions/1000118/what-is-software-properties-common
  - python3-pip
  # - bc #  bc - An arbitrary precision calculator language
  # - open-vm-tools
  # - qemu-guest-agent
package_reboot_if_required: true
runcmd:
  # - echo "RUN_CMD\n$(date +"%T.%N")" > /home/notroot/run.log
  # - echo "\nRUN" >> /home/notroot/.bashrc
  - >
    echo "\nPS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\[\033[01;35m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]'" >> /home/notroot/.bashrc
  # - echo -e "LATE_CMD\n$(date +"%T.%N")" > /home/notroot/late.log
  # - echo -e "\nLATE" >> /home/notroot/.bashrc
  - 'echo "\nPS1=''\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\[\033[01;35m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]''" >> /home/notroot/.bashrc'
