#cloud-config
hostname: ansible-u2004-server
manage_etc_hosts: true
fqdn: ubuntu-server-2004.local.lab
timezone: America/Chicago

#####
# Add groups to the system
# The following example adds the ubuntu group with members 'root' and 'sys'
# and the empty group notroot.
groups:
  - notroot
  # - ubuntu: [root, sys]
  # - notroot: [notroot]
#####

#####
# https://github.com/canonical/cloud-init/blob/main/doc/examples/cloud-config-user-groups.txt
#####
# Add users to the system. Users are added after groups are added.
# Note: Most of these configuration options will not be honored if the user
#       already exists. Following options are the exceptions and they are
#       applicable on already-existing users:
#       - 'plain_text_passwd', 'hashed_passwd', 'lock_passwd', 'sudo',
#         'ssh_authorized_keys', 'ssh_redirect_user'.
# Default user creation:
#
# Unless you define users, you will get a 'ubuntu' user on ubuntu systems with the
# legacy permission (no password sudo, locked user, etc). If however, you want
# to have the 'ubuntu' user in addition to other users, you need to instruct
# cloud-init that you also want the default user. To do this use the following
# syntax:
#   users:
#     - default
#     - bob
#     - ....
#  foobar: ...
#
# users[0] (the first user in users) overrides the user directive.
#
# The 'default' user above references the distro's config:
# system_info:
#   default_user:
#     name: Ubuntu
#     plain_text_passwd: 'ubuntu'
#     home: /home/ubuntu
#     shell: /bin/bash
#     lock_passwd: True
#     gecos: Ubuntu
#     groups: [adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev]
#####

# user: notroot
# # generate with mkpasswd -m sha-512 --rounds=4096 $(pass Homelab/proxmox/users/automation@pve)
# # password: obQ2uKo7pGgRHE15shmXNsJzk
# password: "$6$rounds=4096$FBDc7Tr2pawaO$CvC8LS3ItljMWGUtZHc0XXxs3x16lFeoeYrHQcyUqF6dc8HDacJ39APzCwrTDVaenjD1SZgINTg9noLoGHx2V1"

users:
  - default
  - name: notroot
    gecos: NotRoot
    # passwd: notroot
    # passwd: obQ2uKo7pGgRHE15shmXNsJzk
    passwd: $6$rounds=4096$FBDc7Tr2pawaO$CvC8LS3ItljMWGUtZHc0XXxs3x16lFeoeYrHQcyUqF6dc8HDacJ39APzCwrTDVaenjD1SZgINTg9noLoGHx2V1
    lock_passwd: false
    primary-group: notroot
    groups: notroot,adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev,lxd
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    # ssh_import_id: "gh:proxmox"
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHNqLSuUBuN23f+/h+hVEA+0r7+mdX5+3D99g9tJoE38 proxmox
#####

#####
#https://github.com/canonical/cloud-init/blob/main/doc/examples/cloud-config-ssh-keys.txt
#####
# By default, the fingerprints of the authorized keys for the users
# cloud-init adds are printed to the console. Setting
# no_ssh_fingerprints to true suppresses this output.
no_ssh_fingerprints: true

# By default, (most) ssh host keys are printed to the console. Setting
# emit_keys_to_console to false suppresses this output.
ssh:
  # emit_keys_to_console: false
  # For now we install openssh-server during package installs
  install-server: true
  allow-pw: true

ssh_pwauth: yes

# # add each entry to ~/.ssh/authorized_keys for the configured user or the
# # first user defined in the user definition directive.
# ssh_authorized_keys:
#   - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHNqLSuUBuN23f+/h+hVEA+0r7+mdX5+3D99g9tJoE38 proxmox

chpasswd:
  expire: False
# # list: |
# #   ubuntu:$6$JRWPNckuCpg$kb3/eoXAgiYOiBEFejpB.kItBpnRrEqrxYtuQQZoDrlmqF4.mrhUKFbnLqAZrSSUsay5eDjUM8.b6/5eUr.Ca0
# #   notroot:$6$iLOJTxmjd$dm36v8Z8vxwZQe7gCy.XSoex.g2ZNnwdi7KzYjOdJiZbrYRC7BEA2YSBHN4r.nqjuX07EUdvCjYPq72jWSfnB/
# #   root:$6$fn/XMZ7Dtm.$GUy5gcVK0zaNPv8yFzNWN6uufRKgoMSJJSXE3wYJTfWuVpzYkbxNWYrhL0hG2wILWOQXsRtzXNxtt3vQRYQOA/

package_update: true
package_upgrade: true
packages:
  - curl
  - wget
  - lsb-release
  - openssh-server
  - ca-certificates # https://askubuntu.com/questions/857476/what-is-the-use-purpose-of-the-ca-certificates-package
  - ntp # network time protocol
  - vim
  - jq
  - zip
  - unzip
  - gnupg2
  - software-properties-common # https://askubuntu.com/questions/1000118/what-is-software-properties-common
  - python3-pip
  - qemu-guest-agent
  - pwgen
  - whois
  - tmux
  - autossh
  - python3
  - fail2ban
  # - bc #  bc - An arbitrary precision calculator language
package_reboot_if_required: true
runcmd:
  - echo "RUN_CMD\n$(date +"%T.%N")" > /home/notroot/run.log
  # - echo "\nRUN" >> /home/notroot/.bashrc
  - >
    echo "\nPS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u\[\033[01;34m\]@\[\033[01;35m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" >> /home/notroot/.bashrc
  # - echo -e "LATE_CMD\n$(date +"%T.%N")" > /home/notroot/late.log
  # - echo -e "\nLATE" >> /home/notroot/.bashrc
  - 'echo "\nPS1=''\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u\[\033[01;34m\]@\[\033[01;35m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ ''" >> /home/notroot/.bashrc'
  - systemctl enable --now qemu-guest-agent
  - systemctl start --now qemu-guest-agent

  # - sed -i 's/[#]*Port 22/Port 9726/g' /etc/ssh/sshd_config
  # - sed -i 's/[#]*PermitRootLogin yes/PermitRootLogin prohibit-password/g' /etc/ssh/sshd_config
  # - sed -i 's/[#]*PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
  # - sed -i 's/#HostKey \/etc\/ssh\/ssh_host_ed25519_key/HostKey \/etc\/ssh\/ssh_host_ed25519_key/g' /etc/ssh/sshd_config
  # - systemctl reload ssh
  # - echo 'notroot ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/notroot

# [Cloud-init – Part 2 – Advanced Ubuntu](https://www.lucd.info/2019/12/07/cloud-init-part-2-advanced-ubuntu/)
#   # - netplan --debug apply
#   # - sysctl -w net.ipv6.conf.all.disable_ipv6=1
#   # - sysctl -w net.ipv6.conf.default.disable_ipv6=1
#   - apt-get -y update
#   - add-apt-repository universe
#   # PowerShell
#   - wget https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/installpsh-debian.sh
#   - chmod 755 installpsh-debian.sh
#   - ./installpsh-debian.sh
#   # Git
#   - git config --global user.name "shortpoet"
#   - git config --global user.email "soriano.carlitos@gmail.com"
#   - mkdir -p /home/notroot/source/repos/dots
#   - chown -R notroot:notroot /home/notroot/source/repos/dots
#   - git clone https://github.com/shortpoet/dots /home/notroot/source/repos/dots

#   - apt clean -y
#   - apt autoremove --purge -y

# base config from using install.sh > 998 (2004clone-cloud-init) 9002
# # cat /etc/netplan/50-cloud-init.yaml
# network:
#     version: 2
#     ethernets:
#         eth0:
#             addresses:
#             - 192.168.1.99/24
#             gateway4: 192.168.1.1
#             match:
#                 macaddress: f6:cf:0c:3f:ab:a7
#             nameservers:
#                 addresses:
#                 - 192.168.1.1
#                 search:
#                 - shortpoet.com
#             set-name: eth0
# has more fields than ansible
# network:
#     version: 2
#     ethernets:
#         eth0:
#             dhcp4: true
#             match:
#                 macaddress: 6e:57:32:f7:40:2e
#             set-name: eth0
# # or packer which uses ens18
# # notroot@packer-u2004-server:~$ cat /etc/netplan/00-installer-config.yaml
# # This is the network config written by 'subiquity'
# network:
#   ethernets:
#     ens18:
#       critical: true
#       dhcp-identifier: mac
#       dhcp4: true
#       nameservers:
#         addresses:
#         - 192.168.1.1
#         search:
#         - localdomain
#   version: 2
# write_files:
# - path: /etc/netplan/50-cloud-init.yaml
#   content: |
#     network:
#      version: 2
#      ethernets:
#       ens192:
#        addresses: [192.168.10.82/24]
#        gateway4: 192.168.10.1
#        dhcp6: false
#        nameservers:
#          addresses:
#            - 192.168.10.2
#            - 192.168.10.3
#          search:
#            - local.lab
#        dhcp4: false
#        optional: true
# - path: /etc/sysctl.d/60-disable-ipv6.conf
#   owner: root
#   content: |
#     net.ipv6.conf.all.disable_ipv6=1
#     net.ipv6.conf.default.disable_ipv6=1
# # # network:
# # #   renderers: ['netplan', 'eni', 'sysconfig']
# # #   ethernets:
# # #     eth0:
# # #       dhcp4: true
# # #   version: 2

power_state:
  delay: now
  mode: reboot
  message: Rebooting the OS
  condition: if [ -e /var/run/reboot-required ]; then exit 0; else exit 1; fi
